/**
 * S3 — the district view.
 *
 * Every other screen answers a question about one claim. This one answers the
 * question an officer asks before opening any claim: what does the register as a
 * whole look like, and how much of it does the engine actually know?
 *
 * ## Why the refusal panel is first
 *
 * The obvious district dashboard for this programme is four confident numbers —
 * mean NDVI change, rainfall, share assessed, share escalated — and for this
 * data three of them cannot be computed honestly. `/api/v1/analytics` therefore
 * returns a `refused` list: every metric deliberately not computed, with its
 * reason, generated by the same code path that computes the rest. It is rendered
 * above the figures rather than below them because it is the argument, not the
 * caveat. A reader who sees the counts first and the limits last has already
 * formed the impression the limits exist to prevent.
 *
 * ## Why there are no charts
 *
 * `TemporalControlChart` is hand-rolled SVG for one specific claim-level story:
 * a site line against a control band, where the whole point is that the two
 * overlap. Nothing on this screen has that shape. A second charting approach —
 * let alone a charting dependency — would be a second convention for the same
 * job, and a bar chart of eight counts carries no information the eight counts
 * do not. Tables and figures only.
 *
 * ## Why every zero is printed
 *
 * The server sends all eight epistemic levels and all six evidence families
 * including the empty ones, and this screen renders them. An omitted band reads
 * as a band that does not exist, and the ladder's shape — how much lands at N1,
 * how little reaches L4 — is the product.
 */

import { useEffect, useState } from "react";
import { ApiError, get } from "../lib/api";

/** The eight levels, strongest first. Written out rather than taken from the
 *  response keys so the order is the ladder's and not the server's iteration
 *  order, and so a band the server stopped sending is visibly absent. */
const LADDER = [
  "L4_control_differenced",
  "L3_multi_indicator",
  "L2_corroborated",
  "L1_observed",
  "L0_recorded",
  "N1_inconclusive",
  "N2_unsupported",
  "N3_contradicted",
] as const;

/** Engine order (`services/reconcile/types.FAMILIES`), not alphabetical.
 *  Alphabetical would put `photo` second and quietly imply it carries weight;
 *  it carries the least, because the photograph is the claim's own source. */
const FAMILIES = [
  "terrain",
  "satellite",
  "temporal",
  "photo",
  "control",
  "context",
] as const;

interface FamilyBreakdown {
  /** The denominator. `agreeing + neutral + disagreeing` partitions exactly
   *  this, and a family that was never observed is in none of the three. */
  available: number;
  agreeing: number;
  neutral: number;
  disagreeing: number;
}

interface AnalyticsResponse {
  district_lgds: string[];
  totals: {
    claims: number;
    verdicts: number;
    adjudicated: number;
    provisional: number;
  };
  by_level: Record<string, number>;
  by_action: Record<string, number>;
  /** Null, never 0, when there is nothing to average. Zero is a measurement. */
  means: {
    confidence: number | null;
    coverage: number | null;
    data_sufficiency: number | null;
  };
  detectability: { passed: number; not_passed: number };
  provenance: { measured: number; golden: number };
  families: Record<string, FamilyBreakdown>;
  /** Unrounded share of newest verdicts at N1. Null when there are none. */
  inconclusive_share: number | null;
  refused: string[];
}

/** A share of a total, or an em dash when the total is zero.
 *
 *  `0.0%` of nothing is not a percentage. The dash is the same distinction the
 *  server makes by sending `null` means, kept here so a client-side ratio cannot
 *  reintroduce the zero the API refused to invent. */
const share = (n: number, total: number) =>
  total === 0 ? "—" : `${((n / total) * 100).toFixed(1)}%`;

/** A mean, or the reason it is absent. Never 0.000.
 *
 *  The server distinguishes "the engine assessed claims and found no support"
 *  from "the engine assessed nothing", and this is the only place that
 *  distinction becomes visible to a reader. */
const meanOf = (value: number | null) =>
  value === null ? (
    <span className="note">not measured — no verdicts in scope to average</span>
  ) : (
    <span className="mono">{value.toFixed(3)}</span>
  );

export function Analytics() {
  const [data, setData] = useState<AnalyticsResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    get<AnalyticsResponse>("/api/v1/analytics")
      .then((body) => {
        if (!cancelled) setData(body);
      })
      .catch((err: unknown) => {
        // The engine's own rejection reason, not "something went wrong". An
        // officer told the request failed has nothing to act on; told "your
        // account cannot read verdicts" they have.
        if (!cancelled) setError(err instanceof ApiError ? err.detail : String(err));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (data === null) {
    return (
      <div className="screen">
        <header className="screen-head rise">
          <div>
            <h1>Analytics</h1>
          </div>
        </header>
        {error === null ? (
          <p className="loading">Loading district aggregates…</p>
        ) : (
          <p className="error-inline">Aggregates could not be read: {error}</p>
        )}
      </div>
    );
  }

  const { totals, by_level, by_action, means, detectability, provenance, families } = data;
  const actions = Object.keys(by_action).sort();
  // Levels the server counted that this file does not know about. Rendered
  // rather than dropped: if the ladder gains a ninth band, it must appear here
  // before somebody notices it is missing.
  const extraLevels = Object.keys(by_level).filter(
    (key) => !(LADDER as readonly string[]).includes(key),
  );
  const extraFamilies = Object.keys(families).filter(
    (key) => !(FAMILIES as readonly string[]).includes(key),
  );
  // The detectability gate is recorded as 'passed' or 'failed' on the claim, and
  // is null for a claim ingested before the gate ran. The server counts those as
  // neither rather than inventing a result, so the two counts need not sum to
  // the claim total — and the gap is stated instead of leaving a reader to
  // subtract and wonder.
  const gateRecorded = detectability.passed + detectability.not_passed;

  return (
    <div className="screen">
      <header className="screen-head rise">
        <div>
          <h1>Analytics</h1>
          <p className="sub">
            {totals.verdicts} newest verdicts over{" "}
            <strong className="mono">{totals.claims}</strong> claims in{" "}
            {data.district_lgds.length === 0
              ? "no district"
              : `district ${data.district_lgds.join(", ")}`}
            . One verdict per claim — superseded versions are not counted.
          </p>
        </div>
      </header>

      {/* The most important element on the screen. First, not last. */}
      <div className="panel strip-panel rise">
        <h2>What this page does not claim</h2>
        <p className="note">
          Computed alongside the figures below, not written by hand. Each entry is
          a metric this system declines to produce, with the reason it cannot be
          produced from the rows it holds. A dashboard that showed these numbers
          anyway would be a drawing of a measurement.
        </p>
        <ul className="admin-notes">
          {data.refused.map((entry) => {
            const [metric, ...rest] = entry.split(" — ");
            return (
              <li key={entry}>
                {rest.length === 0 ? (
                  entry
                ) : (
                  <>
                    <strong>{metric}</strong> — {rest.join(" — ")}
                  </>
                )}
              </li>
            );
          })}
        </ul>
      </div>

      <div className="panel strip-panel rise">
        <h2>Register</h2>
        <dl className="strip">
          <div>
            <dt className="label">claims</dt>
            <dd className="figure mono">{totals.claims}</dd>
          </div>
          <div>
            <dt className="label">newest verdicts</dt>
            <dd className="figure mono">{totals.verdicts}</dd>
          </div>
          <div>
            <dt className="label">awaiting reconciliation</dt>
            <dd className="figure mono">{totals.claims - totals.verdicts}</dd>
          </div>
          <div>
            <dt className="label">signed</dt>
            <dd className="figure mono">{totals.adjudicated}</dd>
          </div>
          <div>
            <dt className="label">provisional</dt>
            <dd className="figure mono">{totals.provisional}</dd>
          </div>
        </dl>
        <p className="note">
          <strong>Signed</strong> counts a human decision in the append-only
          adjudication ledger, not a status flag on the verdict — a flag can be
          forgotten, a hash-chained row cannot. Claims awaiting reconciliation are
          shown because hiding them would make the register look more complete
          than it is.
        </p>
      </div>

      <div className="panel strip-panel rise">
        <h2>Inconclusive share</h2>
        <dl className="strip">
          <div>
            <dt className="label">at N1_inconclusive</dt>
            <dd className="figure mono">
              {data.inconclusive_share === null
                ? "—"
                : `${(data.inconclusive_share * 100).toFixed(1)}%`}
            </dd>
          </div>
          <div>
            <dt className="label">of newest verdicts</dt>
            <dd className="figure mono">{totals.verdicts}</dd>
          </div>
        </dl>
        <p className="note">
          Reported prominently on purpose.{" "}
          <strong>
            A system that reports 30% inconclusive is more trustworthy than one
            that reports 100% conclusive
          </strong>{" "}
          — the second has either perfect data or a rule with no way to say "I do
          not know". N1 is a data gap, not a weak finding, and it is the reason
          this page exists rather than a score.
        </p>
      </div>

      <div className="table-wrap panel rise">
        <table className="register">
          <thead>
            <tr>
              <th>Epistemic level</th>
              <th className="num">Verdicts</th>
              <th className="num">Share</th>
            </tr>
          </thead>
          <tbody>
            {[...LADDER, ...extraLevels].map((level) => {
              // Code and word both, as the register and the queue do it: a
              // reader who cannot separate the ladder's hues still gets the band
              // from the text beside the chip's colour.
              const parts = level.split("_");
              // `?? level` is not defensive noise: the chip's ladder colour is
              // keyed off this attribute, so an undefined here would render a
              // colourless chip and say nothing about why.
              const code = parts[0] ?? level;
              const rest = parts.slice(1);
              return (
                <tr key={level}>
                  <td>
                    <span className="chip sm" data-level={code}>
                      {code} {rest.join(" ")}
                    </span>
                  </td>
                  <td className="num mono">{by_level[level] ?? 0}</td>
                  <td className="num mono">{share(by_level[level] ?? 0, totals.verdicts)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <p className="triage-note note">
        All eight bands, including the empty ones. The ladder's ceiling is{" "}
        <span className="mono">L4_control_differenced</span>: the engine can say a
        change is real and is not explained by the regional trend, and it cannot
        say the work caused it. There is no level above L4 to reach.
      </p>

      <div className="table-wrap panel rise">
        <table className="register">
          <thead>
            <tr>
              <th>Recommended action</th>
              <th className="num">Verdicts</th>
              <th className="num">Share</th>
            </tr>
          </thead>
          <tbody>
            {actions.map((action) => (
              <tr key={action}>
                <td className="mono">{action.replace(/_/g, " ")}</td>
                <td className="num mono">{by_action[action]}</td>
                <td className="num mono">{share(by_action[action] ?? 0, totals.verdicts)}</td>
              </tr>
            ))}
          </tbody>
        </table>
        {actions.length === 0 && (
          <p className="empty">
            No verdicts in scope, so the engine recommended nothing. Not zero
            actions — no assessment.
          </p>
        )}
      </div>
      <p className="triage-note note">
        The strongest recommendation this system can make is physical
        verification. It never concludes anything about a person.
      </p>

      <div className="panel strip-panel rise">
        <h2>Means over the newest verdicts</h2>
        <dl className="formula">
          <div>
            <dt>confidence</dt>
            <dd>{meanOf(means.confidence)}</dd>
          </div>
          <div>
            <dt>coverage</dt>
            <dd>{meanOf(means.coverage)}</dd>
          </div>
          <div>
            <dt>data sufficiency</dt>
            <dd>{meanOf(means.data_sufficiency)}</dd>
          </div>
        </dl>
        <p className="note">
          An absent mean is printed as <strong>not measured</strong>, never as
          0.000. Zero is a finding — it would say the engine assessed claims and
          found no support. An empty scope says it assessed nothing, and the two
          must not look alike.
        </p>
      </div>

      <div className="panel strip-panel rise">
        <h2>Detectability gate and provenance</h2>
        <dl className="strip">
          <div>
            <dt className="label">gate passed</dt>
            <dd className="figure mono">{detectability.passed}</dd>
          </div>
          <div>
            <dt className="label">gate not passed</dt>
            <dd className="figure mono">{detectability.not_passed}</dd>
          </div>
          <div>
            <dt className="label">measured</dt>
            <dd className="figure mono">{provenance.measured}</dd>
          </div>
          <div>
            <dt className="label">golden-case</dt>
            <dd className="figure mono">{provenance.golden}</dd>
          </div>
        </dl>
        <p className="note">
          The gate asks whether a structure is large enough to be visible at all
          before any imagery is read; a claim below the sensor limit is assessed
          at cluster scale and said so. The gate result is recorded for{" "}
          <span className="mono">{gateRecorded}</span> of{" "}
          <span className="mono">{totals.claims}</span> claims — the remainder
          were ingested before it ran, and mapping them onto "not passed" would
          invent a sensor-physics result.
        </p>
        <p className="note">
          <strong>Golden-case</strong> rows are synthetic evidence bundles with
          engine-computed verdicts, present because they exercise all eight
          levels. They are counted separately from measured rows here for the same
          reason they are badged in the register: a synthetic row must never be
          mistaken for a measurement.
        </p>
      </div>

      <div className="table-wrap panel rise">
        <table className="register">
          <thead>
            <tr>
              <th>Evidence family</th>
              <th className="num">Available</th>
              <th className="num">Agreeing</th>
              <th className="num">Neutral</th>
              <th className="num">Disagreeing</th>
            </tr>
          </thead>
          <tbody>
            {[...FAMILIES, ...extraFamilies].map((family) => {
              const f = families[family] ?? {
                available: 0,
                agreeing: 0,
                neutral: 0,
                disagreeing: 0,
              };
              return (
                <tr key={family}>
                  <td>{family}</td>
                  <td className="num mono">{f.available}</td>
                  <td className="num mono">{f.agreeing}</td>
                  <td className="num mono">{f.neutral}</td>
                  <td className="num mono">{f.disagreeing}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <p className="triage-note note">
        <strong>Available is the denominator.</strong> Agreeing, neutral and
        disagreeing partition it exactly; a family that was not observed appears
        in none of the three, because "we did not look" is not a neutral reading —
        that distinction is the whole reason coverage exists. The bands are the
        engine's own published thresholds, <span className="mono">±0.350</span> on
        a signed agreement in <span className="mono">[-1, 1]</span>, so these
        counts are the counts the level rules used. Order is the engine's:
        independent evidence first, <span className="mono">photo</span> last and
        weighted lowest, because the photograph is the claim's own source and
        cannot corroborate itself.
      </p>

      <p className="foot-note rise">
        Every figure on this page is an aggregate over stored verdicts and stored
        evidence rows in your jurisdiction. Nothing here is recomputed, sampled or
        extrapolated: each number can be walked back to the claims it came from
        through the register.
      </p>
    </div>
  );
}
